a = input('O que isto é?: ')
print('Tipo primitivo', type(a))
print('Espaços?', a.isspace())
print('É um número?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('É alfanumérico?', a.isalnum())
print('Está em maísculas?', a.isupper())
print('Está em minúsculas?', a.islower())
print('Está capitalizada?', a.istitle())
print('Informações sobre um determinado termo digitado.')
