n = int(input('Digite um valor em metro: '))
print('A medida de {}m corresponde a:'.format(n))
print('{}mm;'.format(n * 1000))
print('{}cm;'.format(n * 100))
print('{}dm;'.format(n * 10))
print('{}dam;'.format(n / 10))
print('{}hm;'.format(n / 100))
print('{}km;'.format(n / 1000))
print('Feito em 11/12/2021, como conversor de medidas.')
